# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SHOWCASE_ENV: lol
jobs:
  build:
    name: TODO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: command
        run: echo ${{ env.SHOWCASE_ENV }}
      - id: show-pipeline-environement
        run: ls
        name: hendrik 
      - run: docker build . --tag hendrikwat/cloudcase_dashboard:0.0.1
      - run: docker login -u hendrikwat -p Samsung123
      - run: docker push "Sanya2810/cloudcase_dashboard"
